### PR TITLE
Tian update notebook

### PR DESCRIPTION
**Pull request by gantian127**
Update notebooks for cem, hydrotrend, and hydrotrend_Ganges
Update the docs to add launch binder link for hydrotrend_Ganges notebook

### CODE REVIEW

**Comment by mdpiper** [comment]
@gantian127 I think this branch needs to be rebased on @mcflugen's recent changes. Let me know if I can help with this.

**Comment by gantian127** [comment]
@mdpiper Thanks for letting me know. Sorry that I didn't notice the new change. I will update my branch.

**Comment by mcflugen** [comment]
@gantian127 A few things before merging:

* [ ] Remove the *Hydrotred* output files from the *Ganges* folder. These shouldn't be under version control, particularly the binary files.
* [ ] Many of the comments in the *Hydrotrend_Ganges* notebook would be better as separate cells of markup.
* [ ] Save the note notebooks without output.

**Comment by gantian127** [comment]
@mcflugen Thanks a lot for your check. I will work on it today.

**Comment by mcflugen** [comment]
👍 Looks good @gantian127

**Pull request merged**
