### PR TITLE
Update location of test netCDF data files

### LINKED ISSUE #150: Test netCDF files not found
The tests in [test_ugrid_read.py](https://github.com/csdms/pymt/blob/master/tests/printers/nc/test_ugrid_read.py) rely on a set of netCDF files on a THREDDS data server hosted on the CSDMS web server. However, CSDMS recently purchased a new web server, and we didn't install THREDDS on it. We'll needs another way to access these test files.

### PR DESCRIPTION
**Pull request by mdpiper**
The test netCDF data files were hosted on the CSDMS THREDDS server, but now reside at https://csdms.colorado.edu/data/.

This fixes #150.

### CODE REVIEW

**Comment by mdpiper** [comment]
@mcflugen It was easier to change host site for the test files than to change the test code. Lmk if this is not cool.

**Comment by mdpiper** [comment]
Coveralls sign issue causing test to fail is annoying.

**Comment by mcflugen** [comment]
@mdpiper I think it makes more sense to include the data files in the repository, so I updated the tests.

**Comment by mdpiper** [comment]
@mcflugen Sounds good. If I don't hear from you in the next hour or so, I'll merge this PR. (Lazy consensus!)

**Pull request merged**
