### PR TITLE
Use relative_files configuration for coveralls

### PR DESCRIPTION
**Pull request by mdpiper**
This PR attempts to fix the successful, but 0%, coverage score reported by Coveralls through the [coveralls-python](https://github.com/marketplace/actions/coveralls-python) Action.

### CODE REVIEW

**Comment by mcflugen** [comment]
@mdpiper I've forgotten how exactly we test our coverage. It looks like it is part of our *ubuntu* and Python 3.9 Test action but yet it also shows up as two separate tests (one of which is failing).

**Comment by mdpiper** [comment]
@mcflugen The failure is only a nominal sign error (-0.0%). I've seen this before with Coveralls, plus the only change from the successful commit prior to this was an update to the changelog.

**Comment by mcflugen** [comment]
@mdpiper I guess my real question is, why do those two coveralls checks show up as separate entries at all? Should they not be part of the *Test / build-and-test (ubuntu-latest, 3.9)* check? Are we running extra coveralls checks that we don't need to?

**Comment by mdpiper** [comment]
@mcflugen I'm not going to guess at what Coveralls or the coveralls-python Action are doing, but AFAIK we're following the directions.

**Comment by mdpiper** [comment]
@mcflugen On Coveralls, there's one [job](https://coveralls.io/jobs/87849922) listed under a [build](https://coveralls.io/builds/43260225) (these are the two links we see in the test results). My hunch is that since coveralls-python is built for parallel testing, the build is a container for holding multiple testing jobs in a commit, while the one job is our test, run in serial. This also may explain the label "false", since 
```yaml
with:
  parallel: false
```
is assumed by coveralls-python since we didn't set it in the action. It seems likely that Coveralls is only called once.

**Comment by mcflugen** [comment]
@mdpiper sounds good. 👍

**Review by mcflugen — APPROVED** [review]
👍

**Pull request merged**
